### PR TITLE
Updated NFS Mount Options for efs backup

### PR DESCRIPTION
**Pull request by rshade**
Updated NFS mount options per: http://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-general.html.

### CODE REVIEW

**Comment by rshade** [comment]
@awsdan can you review? or help me on merge?

**Review by awsdan — APPROVED** [review]
Looks good, thanks!

**Comment by rshade** [comment]
do you know how merges it?

**Comment by awsdan** [comment]
I'll follow up with you on that. Thanks for your patience :)

**Comment by dchymko** [comment]
FYI I think this might have broken it working on Data Pipelines. See #65

**Pull request merged**
